name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          docker ps -a

          docker ps -a --filter "ancestor=capstone-frontend" --format "{{.ID}}" | xargs -r docker stop
          docker system prune -af
          
          docker ps -a

          cd Desktop/Coding/CSCE_481/CSCE-482-Capstone
          git pull origin main

          docker build --network=host -t capstone-frontend .
          docker run -d --restart unless-stopped -p 58398:3000 capstone-frontend
          EOF